### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by benedictjohannes** [stackrox/go-grpc-http1#18]
I haven't been able to found more detail, so pardon this question via issue. As this is a websocket solution, this should enable all gRPC features over websocket, including bidirectional / client streaming.

So, I'd like to ask, are there any browser (JS) client implementation for this implementation of gRPC-WebSocket?

If there isn't (yet), is there any plan to develop one?

As modern web frameworks are rapidly evolving and more things can be achieved in-browser, being able to use gRPC in browser would be awesome, as IMO restricting gRPC for server-to-server only is quite a limiting view.

**Comment by RTann** [comment]
I'm definitely no browser nor JS expert, bit it sounds like the full gRPC features cannot currently be done in the browser due to [gRPC's reliance on HTTP/2](https://grpc.io/blog/state-of-grpc-web/#the-grpc-web-spec).

Unfortunately I do not know of any gRPC protocol which supports client-side nor bi-di streams. From what I can tell, the official gRPC-Web protocol is just going to wait for the [whatwg streams API](https://github.com/whatwg/streams). It seems like even https://github.com/improbable-eng/grpc-web does not plan on implementing this until the streams API is available (though, there was a [POC](https://github.com/improbable-eng/grpc-web/pull/1084) at one point). I know we do not plan on implementing this because it is not needed for the [StackRox project](https://github.com/stackrox/stackrox).

I'm sorry I was unable to respond with any good news for you, but hopefully that streams API will come into fruition soon!
